---
title: "R Notebook"
output: html_notebook
---

```{r - libraries }

library(dplyr)
library(lubridate)
library(ggplot2)
library(ggsignif)
library(ggbeeswarm)
library(multimode)
library(psych)
library(car)
library(e1071)
library(tidyverse)
library(ggcorrplot)
library(kableExtra)
library(mgcv)
library(robustbase)
library(mia)

```

```{r - upload dependencies }

source("C:/Users/bm00900/OneDrive - University of Surrey/Desktop/Ph.D/DMA study/Data/Workspace.1/Scripts/Distr_visualization_utils.R")
source("C:/Users/bm00900/OneDrive - University of Surrey/Desktop/Ph.D/DMA study/Data/Workspace.1/Scripts/Gm_utils.R")

```


```{r - upload data }

ag <-  read.delim("C:/Users/bm00900/OneDrive - University of Surrey/Desktop/Ph.D/DMA study/Data/Workspace.1/Data/Raw/Actigraph data_all.txt")
in24_merged_VIF <- readRDS("C:/Users/bm00900/OneDrive - University of Surrey/Desktop/Ph.D/DMA study/Data/Workspace.1/Data/Processed/in24_merged_VIF.rds")
FFQ_p_ni_t1.adj_scaled <- readRDS("C:/Users/bm00900/OneDrive - University of Surrey/Desktop/Ph.D/DMA study/Data/Workspace.1/Data/Processed/FFQ_p_ni_t1.adj_scaled.rds")
in24_nutr_t1.adj <- readRDS("C:/Users/bm00900/OneDrive - University of Surrey/Desktop/Ph.D/DMA study/Data/Workspace.1/Data/Processed/in24_nutr_t1.adj.rds")
metadata_t1 <- readRDS("C:/Users/bm00900/OneDrive - University of Surrey/Desktop/Ph.D/DMA study/Data/Workspace.1/Data/Processed/metadata_t1.rds")
tse_gbm <- readRDS("C:/Users/bm00900/OneDrive - University of Surrey/Desktop/Ph.D/DMA study/Data/Workspace.1/Data/Processed/tse_gbm.rds")
df_p_t1_outcomes <- readRDS("C:/Users/bm00900/OneDrive - University of Surrey/Desktop/Ph.D/DMA study/Data/Workspace.1/Data/Processed/df_p_t1_outcomes.rds")
tse_taxa_sub30 <- readRDS("C:/Users/bm00900/OneDrive - University of Surrey/Desktop/Ph.D/DMA study/Data/Workspace.1/Data/Processed/tse_taxa_sub30.rds")

```

```{r - preprocess & filter }

# preprocess
ag <- ag[1:132, 1:40]
ag$ID <- tolower(ag$ID)
ag$ID <- gsub("p0*(\\d+)", "p\\1", ag$ID)

# h col
ag$Average.Wear.Time.Day..h.m.s. <- hms(ag$Average.Wear.Time.Day..h.m.s.)
ag$Average.Wear.Time.Day..h.m.s. <- round(
  as.numeric(ag$Average.Wear.Time.Day..h.m.s.) / 3600, 2)

# filter: keep pp with 
# t1
#wear time > 80% 
#h/d > 80% (19.2h) --> #[https://link.springer.com/article/10.1007/s41999-024-01100-z] # wear time / day considered as valid if >= 80%/d
#>= 4 recording days
ag.f <- ag %>%
  filter(Excluded == F & Time.point == 1 & Wear.week.... >= 80 & Average.Wear.Time.Day..h.m.s. >= 19.2 & Exact.recording.days..n. >= 4) # 42 included

# save
saveRDS(ag, "C:/Users/bm00900/OneDrive - University of Surrey/Desktop/Ph.D/DMA study/Data/Workspace.1/Data/Raw/ag_all.rds")

```


```{r - inspect sleep vars }

# sleep vars
sleep_vars <- colnames(ag.f)[c(33, 36, 38, 39)]

# summary
sv_summary <- sapply(ag.f[, sleep_vars], describe)

# long format df for facet wrap
df_long <- pivot_longer(
  ag.f[, c("ID", sleep_vars)],
  cols = -ID,
  names_to = "Var",
  values_to = "Value"
)

# density plot
ggplot(df_long, aes(x = Value)) +
  geom_density(fill = "steelblue", alpha = 0.5) +
    facet_wrap(~Var, 
               scales = "free",
               labeller = labeller(
                 Var = c(
                 Average.Total.Sleep.Time.night..h. = "Total Sleep Time (h)",
                 Average.Number.of.Awakenings.night..n. = "Number of Awakenings",
                 Sleep.Efficiency.... = "Sleep Efficiency (%)",
                 Average.wake.after.sleep.onset.night..min. = "WASO (min)"
               ))) +
  theme(
    strip.text = element_text(face = "bold", size = 15),
    axis.text = element_text(size = 15)
  )

# check bimodality just in case for sleep eff
modetest(ag.f$Sleep.Efficiency....) # not bimodal

# distr
distr_f(ag.f, sleep_vars)


```


####### DIET ANALYSIS

# hei
```{r - visualize sleep vars - HEI }

# merge vars for visualization
df <- dplyr::left_join(ag.f, in24_merged_VIF, by = "ID")

# long df format
df_long <- pivot_longer(
  data = df,
  cols = all_of(sleep_vars),
  names_to = "sleep.vars",
  values_to = "value"
)

# distr plots 
ggplot(df_long, aes(x = HEI_cluster_2, y = value)) +
  geom_violin(aes(fill = HEI_cluster_2), alpha = 0.4, color = NA, trim = FALSE) +
  scale_fill_manual(
    name = "HEI cluster",
    values = c("2" = "#d95f02", "1" = "#1b9e77")) +
  geom_boxplot(outlier.shape = "square") +
  geom_beeswarm(alpha = 0.5, size = 2.5) +
   geom_signif(comparisons = list(c("1", "2")), map_signif_level = TRUE) +
  facet_wrap(~ sleep.vars, scales = "free",
             labeller = labeller(
                 sleep.vars = c(
                 Average.Total.Sleep.Time.night..h. = "Total Sleep Time (h)",
                 Average.Number.of.Awakenings.night..n. = "Number of Awakenings",
                 Sleep.Efficiency.... = "Sleep Efficiency (%)",
                 Average.wake.after.sleep.onset.night..min. = "WASO (min)"
               ))) +
  labs(x = "HEI Cluster") +
  theme(
    strip.text = element_text(face = "bold", size = 15),
    axis.text = element_text(size = 15),
    axis.title = element_text(face = "bold")
  )

# test
lapply(ag.f[, sleep_vars], function(x) t.test(x ~ df$HEI_cluster_2)) # ns

# no differences in sleep vars between HEI groups

```

# st diet
```{r - sleep vars - st diet heatmap }

# define dietary vars
diet_vars <- colnames(df)[c(42: 50)]

sleep_df <- df %>% select(sleep_vars)
diet_df  <- df %>% select(diet_vars)

#names
colnames(sleep_df) <- c("TST (h)", "NWAK", "Sleep Efficiency (%)", "WASO (min)")
colnames(diet_df) <- c("Proteins (g)", "Fibres (g)", "Free Sugars (g)", "Sat FAs (g)", "PUFAs (g)", "Micronutrients (mg)", "Minerals (mg)", "omega-6 / omega-3", "Sat FAs / Unsat FAs")


# perform test
cor <- corr.test(sleep_df, diet_df, method = "spearman", adjust = "fdr")

# heatmap
sleep_st.diet_p <- ggcorrplot(cor$r,
           p.mat = cor$p.adj,
           lab = TRUE,
           lab_size = 5,
           sig.level = 0.2,
           tl.cex = 15,
           insig = "pch",
           pch = "",
           colors = c("blue", "white", "red")) +
  labs(fill = "Spearman coefficient") +
  theme(
    axis.text = element_text(face = "bold", size = 15),
    legend.title = element_text(face = "bold", size = 12),
    legend.text = element_text(size = 12)
  )

```

```{r - control for lmrob }

# set control parameter 

ctrl <- lmrob.control(
  setting = "KS2014")

```

```{r - lmrob models }

# HEI 
summary(lmrob(scale(Sleep.Efficiency....) ~  HEI_cluster_2, data = df)) # ns

# st diet
# Sleep efficiency
se_mod <- apply(df[, diet_vars], 2, function(x) lmrob(scale(Sleep.Efficiency....) ~ x, data =df, control = ctrl))
se_table <- lmrob_table(se_mod, length(diet_vars))

# TST
tst_mod <- apply(df[, diet_vars], 2, function(x) lmrob(scale(Average.Total.Sleep.Time.night..h.) ~ x, data =df, control = ctrl))
tst_table <- lmrob_table(tst_mod, length(diet_vars))

# numb of awakenings
nwak_mod <- apply(df[, diet_vars], 2, function(x) (lmrob(scale(Average.Number.of.Awakenings.night..n.) ~ x, data =df, control = ctrl)))
nwak_table <- lmrob_table(nwak_mod, length(diet_vars))

# WASO 
waso_mod <- apply(df[, diet_vars], 2, function(x) (lmrob(scale(Average.wake.after.sleep.onset.night..min.) ~ x, data =df, control = ctrl)))
waso_table <- lmrob_table(waso_mod, length(diet_vars))

```

```{r - check omega 6 and 3 }

# look at omega 3 and 6
nutr_vars <- colnames(in24_nutr_t1.adj)[12:14]

df3 <- left_join(df, in24_nutr_t1.adj, by = "ID")

nutr_mod <- apply(df3[, nutr_vars], 2, function(x) lmrob(scale(Sleep.Efficiency....) ~ scale(x), data =df3, control = ctrl))
nutr_table <- lmrob_table(nutr_mod, length(nutr_vars))

# nothing

```

```{r - try GAMs }

df <- left_join(df, metadata_t1, by = "ID")

summary(gam(scale(Average.wake.after.sleep.onset.night..min.) ~ s(`Cis.n6_to_Cis.n3`, k = 5), data = df, family = scat(link = "identity"), method = "REML"))

# only linear trends pop out

```


# lt diet 
```{r - sleep vars - lt diet heatmap }

# define vars and df
df2 <- left_join(ag.f, FFQ_p_ni_t1.adj_scaled, by = "ID")
ffq.diet_vars <- colnames(df2)[43:50]
diet_df2  <- df2 %>% select(ffq.diet_vars)

colnames(diet_df2) <- c("Glycemic load", "Carbohydrates (g)", "Sugars (g)", "Fibres(g)", "Proteins (g)", "Fats(g)", "Sat FAs (g)", "Unsat FAs (g)")

# perform test
cor2 <- corr.test(sleep_df, diet_df2, method = "spearman", adjust = "fdr")

# heatmap
sleep_lt.diet_p <- ggcorrplot(cor2$r,
           p.mat = cor2$p.adj,
           lab = TRUE,
           lab_size = 5,
           sig.level = 0.2,
           tl.cex = 15,
           insig = "pch",
           pch = "",
           colors = c("blue", "white", "red")) +
  labs(fill = "Spearman coefficient") +
  theme(
    axis.text = element_text(face = "bold", size = 15),
    legend.title = element_text(face = "bold", size = 12),
    legend.text = element_text(size = 12)
  )

```

```{r - lmrob models lt diet }

# Sleep efficiency
se_mod2 <- apply(df2[, ffq.diet_vars], 2, function(x) lmrob(scale(Sleep.Efficiency....) ~ x, data =df2, control = ctrl))
se_table2 <- lmrob_table(se_mod2, length(ffq.diet_vars))

# TST
tst_mod2 <- apply(df2[, ffq.diet_vars], 2, function(x) lmrob(scale(Average.Total.Sleep.Time.night..h.) ~ x, data =df2, control = ctrl))
tst_table2 <- lmrob_table(tst_mod2, length(ffq.diet_vars))

# numb of awakenings
nwak_mod2 <- apply(df2[, ffq.diet_vars], 2, function(x) (lmrob(scale(Average.Number.of.Awakenings.night..n.) ~ x, data =df2, control = ctrl)))
nwak_table2 <- lmrob_table(nwak_mod2, length(ffq.diet_vars))

# WASO 
waso_mod2 <- apply(df2[, ffq.diet_vars], 2, function(x) (lmrob(scale(Average.wake.after.sleep.onset.night..min.) ~ x, data =df2, control = ctrl)))
waso_table2 <- lmrob_table(waso_mod2, length(ffq.diet_vars))

# nothing

```



####### PSYCHOLOGY 

```{r - anxiety }

stai_mod <- apply(df[, sleep_vars], 2, function(x) lmrob(df$STAI.s_score_scaled ~ x, data =df, control = ctrl))
stai_table <- lmrob_table(stai_mod, length(sleep_vars))

```

```{r - stress & negative affect }

df_ps <- dplyr::left_join(ag.f, df_p_t1_outcomes, by = "ID")

stress_mod <- apply(df_ps[, sleep_vars], 2, function(x) lmrob(scale(DASS.21.s_score) ~ x, data =df_ps, control = ctrl))
stress_table <- lmrob_table(stress_mod, length(sleep_vars))

neg_mod <- apply(df_ps[, sleep_vars], 2, function(x) lmrob(scale(log1p(PANAS_n)) ~ x, data =df_ps, control = ctrl)) # log because it is quite skewed 
neg_table <- lmrob_table(neg_mod, length(sleep_vars))

```


# GBMs
```{r - preprocess }

### 1. subset based on N > 20 & preprocess
sum(rowData(tse_gbm)$N_presence < 20) # include all
df_gbm <- assay(tse_gbm, "clr")

# define feats
feats_gbm <- rownames(df_gbm)

# make names 
feats_gbm <- make.names(feats_gbm)
rownames(df_gbm) <- make.names(rownames(df_gbm))

# preprocess 
df_gbm <- df_gbm %>% t() %>% as.data.frame() %>% rownames_to_column("ID")
df_gbm  <- dplyr::left_join(df, df_gbm, by = "ID")

# 2. zero df based on count
tse_count <- tse_gbm[rowData(tse_gbm)$N_presence >= 20]
rownames(tse_count) <-make.names(rownames(tse_count))
tse_count <- assay(tse_count) %>% t() %>% as.data.frame() %>% rownames_to_column("ID")

tse_count <- tse_count[tse_count$ID %in% df_gbm$ID, ]

identical(df_gbm$ID, tse_count$ID)

```

 
```{r - TST models }

### 2. apply lmrob through each feature including only IDs with feature > 0
# initialize
lmrob_gbm <- setNames(vector("list", length(feats_gbm)), feats_gbm)

# loop for sleep efficiency 
for (feature in feats_gbm) {
  keep <- tse_count[[feature]] > 0  # or >= 0
  df4   <- df_gbm[keep, , drop = FALSE]
  
  # standardize response and predictor inside the subset
  df4$y <- scale(df4$Average.Total.Sleep.Time.night..h.)[,1]
  df4$x <- scale(df4[[feature]])[,1]

  model <- lmrob(y ~ x, data = df4, control = ctrl)

  lmrob_gbm[[feature]] <- list(model = model, N = sum(keep))
}

# extract models
lmrob_gbm_models <- lapply(lmrob_gbm, function(x) x$model)

### 3. table
lmrob_gbm_df <- lmrob_table(lmrob_gbm_models, length(feats_gbm))
lmrob_gbm_df <- lmrob_gbm_df %>% as.data.frame() %>% rownames_to_column("Feature")

# extract Ns
Ns <- sapply(lmrob_gbm, function(x) x$N) %>% as.data.frame() %>% rownames_to_column("Feature")
colnames(Ns)[2] <- "N"

# merge 
lmrob_gbm_df <- dplyr::left_join(lmrob_gbm_df, Ns, by = "Feature")

# rownames
rownames(lmrob_gbm_df) <- lmrob_gbm_df$Feature
rownames(lmrob_gbm_df)<- gsub("[._]", " ", rownames(lmrob_gbm_df))

lmrob_gbm_df <- lmrob_gbm_df[, -1]

```

```{r - SE models }

### 2. apply lmrob through each feature including only IDs with feature > 0
# initialize
lmrob_gbm <- setNames(vector("list", length(feats_gbm)), feats_gbm)

# loop for sleep efficiency 
for (feature in feats_gbm) {
  keep <- tse_count[[feature]] > 0  # or >= 0
  df4   <- df_gbm[keep, , drop = FALSE]
  
  # standardize response and predictor inside the subset
  df4$y <- scale(df4$Sleep.Efficiency....)[,1]
  df4$x <- scale(df4[[feature]])[,1]

  model <- lmrob(y ~ x, data = df4, control = ctrl)

  lmrob_gbm[[feature]] <- list(model = model, N = sum(keep))
}

# extract models
lmrob_gbm_models <- lapply(lmrob_gbm, function(x) x$model)

### 3. table
lmrob_gbm_df <- lmrob_table(lmrob_gbm_models, length(feats_gbm))
lmrob_gbm_df <- lmrob_gbm_df %>% as.data.frame() %>% rownames_to_column("Feature")

# extract Ns
Ns <- sapply(lmrob_gbm, function(x) x$N) %>% as.data.frame() %>% rownames_to_column("Feature")
colnames(Ns)[2] <- "N"

# merge 
lmrob_gbm_df <- dplyr::left_join(lmrob_gbm_df, Ns, by = "Feature")

# rownames
rownames(lmrob_gbm_df) <- lmrob_gbm_df$Feature
rownames(lmrob_gbm_df)<- gsub("[._]", " ", rownames(lmrob_gbm_df))

lmrob_gbm_df <- lmrob_gbm_df[, -1]

```

```{r - NWAK models }

### 2. apply lmrob through each feature including only IDs with feature > 0
# initialize
lmrob_gbm <- setNames(vector("list", length(feats_gbm)), feats_gbm)

# loop for sleep efficiency 
for (feature in feats_gbm) {
  keep <- tse_count[[feature]] > 0  # or >= 0
  df4   <- df_gbm[keep, , drop = FALSE]
  
  # standardize response and predictor inside the subset
  df4$y <- scale(df4$Average.Number.of.Awakenings.night..n.)[,1]
  df4$x <- scale(df4[[feature]])[,1]

  model <- lmrob(y ~ x, data = df4, control = ctrl)

  lmrob_gbm[[feature]] <- list(model = model, N = sum(keep))
}

# extract models
lmrob_gbm_models <- lapply(lmrob_gbm, function(x) x$model)

### 3. table
lmrob_gbm_df <- lmrob_table(lmrob_gbm_models, length(feats_gbm))
lmrob_gbm_df <- lmrob_gbm_df %>% as.data.frame() %>% rownames_to_column("Feature")

# extract Ns
Ns <- sapply(lmrob_gbm, function(x) x$N) %>% as.data.frame() %>% rownames_to_column("Feature")
colnames(Ns)[2] <- "N"

# merge 
lmrob_gbm_df <- dplyr::left_join(lmrob_gbm_df, Ns, by = "Feature")

# rownames
rownames(lmrob_gbm_df) <- lmrob_gbm_df$Feature
rownames(lmrob_gbm_df)<- gsub("[._]", " ", rownames(lmrob_gbm_df))

lmrob_gbm_df <- lmrob_gbm_df[, -1]

```

```{r - WASO models }

### 2. apply lmrob through each feature including only IDs with feature > 0
# initialize
lmrob_gbm <- setNames(vector("list", length(feats_gbm)), feats_gbm)

# loop for sleep efficiency 
for (feature in feats_gbm) {
  keep <- tse_count[[feature]] > 0  # or >= 0
  df4   <- df_gbm[keep, , drop = FALSE]
  
  # standardize response and predictor inside the subset
  df4$y <- scale(df4$Average.wake.after.sleep.onset.night..min.)[,1]
  df4$x <- scale(df4[[feature]])[,1]

  model <- lmrob(y ~ x, data = df4, control = ctrl)

  lmrob_gbm[[feature]] <- list(model = model, N = sum(keep))
}

# extract models
lmrob_gbm_models <- lapply(lmrob_gbm, function(x) x$model)

### 3. table
lmrob_gbm_df <- lmrob_table(lmrob_gbm_models, length(feats_gbm))
lmrob_gbm_df <- lmrob_gbm_df %>% as.data.frame() %>% rownames_to_column("Feature")

# extract Ns
Ns <- sapply(lmrob_gbm, function(x) x$N) %>% as.data.frame() %>% rownames_to_column("Feature")
colnames(Ns)[2] <- "N"

# merge 
lmrob_gbm_df <- dplyr::left_join(lmrob_gbm_df, Ns, by = "Feature")

# rownames
rownames(lmrob_gbm_df) <- lmrob_gbm_df$Feature
rownames(lmrob_gbm_df)<- gsub("[._]", " ", rownames(lmrob_gbm_df))

lmrob_gbm_df <- lmrob_gbm_df[, -1]

```



# species, binary 
```{r - TST }

# extract l6 df and be sure cols are factor 
df5 <- assay(tse_taxa_sub30, "binarized") %>% as.data.frame()
df5 <- df5 %>% mutate(across(everything(), ~ as.factor(.))) %>% t() %>% as.data.frame() %>% rownames_to_column("ID")

# define IVs
l6_feats <- colnames(df5)[-1]

# join
df6 <- dplyr::left_join(df, df5, by = "ID")

# run
lmrob_l6 <- apply(df6[, l6_feats], 2, function(x) lmrob(
    scale(Average.Total.Sleep.Time.night..h.) ~ x,
    data = df6,
    control = ctrl
  )
)

# table
lmrob_l6_df <- lmrob_table(lmrob_l6, length(lmrob_l6))

# friendly names
rownames(lmrob_l6_df) <-  gsub("[._]", " ", rownames(lmrob_l6_df))


```

```{r - SE }

# run
lmrob_l6 <- apply(df6[, l6_feats], 2, function(x) lmrob(
    scale(Sleep.Efficiency....) ~ x,
    data = df6,
    control = ctrl
  )
)

# table
lmrob_l6_df <- lmrob_table(lmrob_l6, length(lmrob_l6))

# friendly names
rownames(lmrob_l6_df) <-  gsub("[._]", " ", rownames(lmrob_l6_df))


```

```{r - NWAK }

# run
lmrob_l6 <- apply(df6[, l6_feats], 2, function(x) lmrob(
    scale(Average.Number.of.Awakenings.night..n.) ~ x,
    data = df6,
    control = ctrl
  )
)

# table
lmrob_l6_df <- lmrob_table(lmrob_l6, length(lmrob_l6))

# friendly names
rownames(lmrob_l6_df) <-  gsub("[._]", " ", rownames(lmrob_l6_df))


```

```{r - WASO }

# run
lmrob_l6 <- apply(df6[, l6_feats], 2, function(x) lmrob(
    scale(Average.wake.after.sleep.onset.night..min.) ~ x,
    data = df6,
    control = ctrl
  )
)

# table
lmrob_l6_df <- lmrob_table(lmrob_l6, length(lmrob_l6))

# friendly names
rownames(lmrob_l6_df) <-  gsub("[._]", " ", rownames(lmrob_l6_df))


```








